import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alpha Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan">Alpha Coder</span>
        </h1>
        <div className={styles.imagewrap}>
          {/* <Image
            className={styles.myImg}
            src="/homeimg.jpg"
            alt="home"
            width={400}
            height={200}
          /> */}
          <img
            className={styles.myImg}
            src="/homeimg.jpg"
            alt="home"
            width={400}
            height={200}
          />
        </div>
        <div className="blog">
          <h2 className={styles.h2}>Popular Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p className={styles.p}>
              JavaScript is a language used to design logic for the web
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p className={styles.p}>
              JavaScript is a language used to design logic for the web
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p className={styles.p}>
              JavaScript is a language used to design logic for the web
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
